recon script modify

diff --git a/shsrc/webtech b/shsrc/webtech
--- a/shsrc/webtech
+++ b/shsrc/webtech
@@ -1,7 +1,6 @@
 #!/bin/bash
 
 #Color Codes
-
 RED='\e[1;31m'
 GREEN='\e[1;32m'
 YELLOW='\e[1;33m'
@@ -10,7 +9,6 @@ CYNE='\e[1;36m'
 RESET='\e[1;0m'
 
 # Input Check
-
 TARGET=$1
 
 if [ -z "$TARGET" ]; then
@@ -21,7 +19,6 @@ if [ -z "$TARGET" ]; then
 fi
 
 # Tools check
-
 TOOLS=("whois" "whatweb" "dig" "waf00f")
 
 for tool in "${TOOLS}"; do
@@ -34,13 +31,11 @@ done
 echo -e "${GREEN}[*] Starting Reconnaissance on: ${TARGET}${RESET}\n"
 
 # Executing Commands
-
 echo -e "${GREEN}[+]Whois lookup${RESET}"
 whois ${TARGET} 2>/dev/null | head -22 || echo -e "${RED}[!] Whois lookup failed"
 
-
 echo -e "\n${YELLOW}[+] Whatweb Scanning...${RESET}"
-whatweb ${TARGET} 2>/dev/null | grep "200 OK" || echo -e "${RED}[!] 200 OK response not found${RESET}"
+whatweb ${TARGET} 2>/dev/null | grep -E "200 OK|302 Found" || echo -e "${RED}[!] 200 OK response not found${RESET}"
 
 echo -e "\n${GREEN}[+] DNS information ${RESET}"
 dig ${TARGET} 2>/dev/null | tail -n+13 | head -3 || echo -e "${RED}[!] DNS info not found ${RESET}"
@@ -51,8 +46,4 @@ dig ${TARGET} ns 2>/dev/null | tail -n+13 | head -3 || echo -e "${RED}[!] Namese
 echo -e "\n${BLUE}[+] WA Firewall Scaning...${RESET}"
 wafw00f ${TARGET} 2>/dev/null | tail -4 || echo -e "${RED}[!] Firewall info not found ${RESET}"
 
-
-echo -e "\n${GREEN} [*] Recon Scan Completed successfully! ${RESET}"
-
-
-
+echo -e "\n${GREEN}[*] Recon Scan Completed successfully! ${RESET}"
